In [108]:
import numpy as np
import numpy.linalg as la
from utils import random_matrix

n = 8
m = 8
r = 4
rng=np.random.default_rng(42)

#A = rng.random((n,m))
A = random_matrix(n,m,r,rng)
print(A)

stol=1e-12

[[ 1.13898125e-01  4.62120874e-01  5.03788395e-01  5.00908267e-02
   3.50378147e-01 -8.69329961e-02 -7.96623440e-04 -1.65840413e-01]
 [ 3.24658514e-01 -2.80580955e-04  4.95749667e-01  2.75718803e-02
  -2.52616999e-01  3.24120594e-01 -1.64750378e-02  1.96938275e-01]
 [ 2.20582439e-01 -4.51347429e-01  3.60702076e-01  4.61293384e-01
   1.68504835e-01 -1.09232003e-02  4.32153441e-01  6.65140072e-02]
 [-8.07190442e-02  3.19230533e-01 -9.91036832e-02  1.36540594e-01
   5.00780093e-01 -1.02757993e-01  2.08560201e-01 -7.56347284e-02]
 [ 4.42039944e-03  3.53138276e-01  5.87729077e-02 -2.51098811e-02
   2.14614170e-01  2.28402220e-02  3.32024512e-03 -2.70517656e-02]
 [ 1.85232624e-01  3.80570828e-01  1.17025180e-02 -1.29482767e-01
  -1.38580535e-01  4.94383371e-01 -3.57174864e-02  3.27830860e-01]
 [ 1.32232469e-02 -3.77089709e-02 -3.45003781e-01  2.10119505e-01
   2.07978936e-01  2.15996699e-01  3.56681949e-01  2.50383522e-01]
 [ 3.23105171e-02  1.22762142e-01 -3.15847047e-01  7.22211182e-02
   

In [109]:
U,S,Vh = la.svd(A)

Smat=np.zeros((n,m))
Smat[:r,:r]=np.diag(S[:r])

#print(la.norm(A-U@Smat@Vh))
print(U)
print(S)
print(Vh)

[[ 4.73025855e-01  4.29903168e-01  4.12376332e-01 -2.49081833e-01
   1.20250594e-01  2.88188658e-01 -4.74070852e-01 -1.92555779e-01]
 [-2.04487816e-01  2.54988435e-02  1.15349183e-01 -7.09990068e-01
  -6.06392546e-01  1.21496485e-01  2.34154784e-01 -5.33050881e-02]
 [ 2.37087755e-01  2.68667815e-01 -6.73699861e-01 -4.82387907e-01
   3.01311628e-01 -2.63395250e-01 -1.18402440e-04  1.57707442e-01]
 [ 6.42480615e-01  2.18131709e-02  5.50354110e-02  1.76523076e-01
  -2.63330007e-01  1.50985577e-01  4.26656372e-01  5.27615916e-01]
 [ 3.06153923e-01  9.94587218e-03  2.86726505e-01 -9.66689478e-03
  -2.82742344e-02 -7.30241638e-01  2.99579308e-01 -4.47286569e-01]
 [-7.03018664e-03 -4.93755742e-01  4.00600449e-01 -4.05082010e-01
   5.75270799e-01  2.87395753e-02  1.59039280e-01  2.72997696e-01]
 [ 3.43599097e-01 -4.62924184e-01 -3.33770875e-01 -2.89176892e-02
   3.31049166e-02  4.29761346e-01  1.56202737e-01 -5.87547093e-01]
 [ 2.31515319e-01 -5.32618450e-01 -7.51273772e-02 -7.06593089e-02
  -

## Column partitioning

Partitioning

In [110]:
A1=A[:,:2]
A2=A[:,2:]

SVD of first block

In [111]:
U1,S1,Vh1 = la.svd(A1)
r1=len(S1[S1>stol])
S1mat=np.zeros((r1,A1.shape[1]))
S1mat[:r1,:r1]=np.diag(S1[:r1])

SVD of second block

In [112]:

U2,S2,Vh2 = la.svd(A2)
r2=len(S2[S2>stol])
S2mat=np.zeros((r2,A2.shape[1]))
S2mat[:r2,:r2]=np.diag(S2[:r2])

Merging

In [113]:
Atil=np.concatenate((U1[:,:r1]@S1mat,U2[:,:r2]@S2mat), axis=1)
Util, Stil, Vhtil = la.svd(Atil)

Stilmat=np.zeros((r,r))
Stilmat[:r,:r]=np.diag(Stil[:r])

newVh=la.inv(Stilmat)@Util[:,:r].T@A

rnew=len(Stil[Stil>stol])

Stilmat2=np.zeros((rnew,Atil.shape[1]))
Stilmat2[:rnew,:rnew]=np.diag(Stil[:r])

newVh21=np.concatenate((Vh1,np.zeros((2,6))), axis=1)
newVh22=np.concatenate((np.zeros((6,2)),Vh2), axis=1)
newVh2=np.concatenate((newVh21,newVh22), axis=0)

#print(Util)
#print(Stil)
#print(Vhtil.shape)
#print(newVh)

print(la.norm(A-Util[:,:r]@Stilmat@newVh))
print(la.norm(A-Util[:,:r]@Stilmat2@Vhtil@newVh2))

1.0966686592008878e-15
2.3340053702916635e-15


## Row partitioning

Partitioning

In [114]:
A1=A[:2,:]
A2=A[2:,:]

print(A2)

[[ 0.22058244 -0.45134743  0.36070208  0.46129338  0.16850484 -0.0109232
   0.43215344  0.06651401]
 [-0.08071904  0.31923053 -0.09910368  0.13654059  0.50078009 -0.10275799
   0.2085602  -0.07563473]
 [ 0.0044204   0.35313828  0.05877291 -0.02510988  0.21461417  0.02284022
   0.00332025 -0.02705177]
 [ 0.18523262  0.38057083  0.01170252 -0.12948277 -0.13858054  0.49438337
  -0.03571749  0.32783086]
 [ 0.01322325 -0.03770897 -0.34500378  0.21011951  0.20797894  0.2159967
   0.35668195  0.25038352]
 [ 0.03231052  0.12276214 -0.31584705  0.07222112  0.09994294  0.30472726
   0.21607895  0.2780134 ]]


First block

In [115]:
U1,S1,Vh1 = la.svd(A1)
r1=len(S1[S1>stol])
S1mat=np.zeros((A1.shape[0],r1))
S1mat[:r1,:r1]=np.diag(S1[:r1])
print(S1mat.shape)
print(U1.shape)

(2, 2)
(2, 2)


Second block

In [116]:
U2,S2,Vh2 = la.svd(A2)
r2=len(S2[S2>stol])
S2mat=np.zeros((A2.shape[0],r2))
S2mat[:r2,:r2]=np.diag(S2[:r2])

print(S2mat.shape)
print(U2.shape)

(6, 4)
(6, 6)


Merging

In [117]:
Atil=np.concatenate((S1mat@Vh1[:r1,:],S2mat@Vh2[:r2,:]), axis=0)
print(Atil.shape)
Util, Stil, Vhtil = la.svd(Atil)


Stilmat=np.zeros((r,r))
Stilmat[:r,:r]=np.diag(Stil[:r])

print(Stilmat)


rnew=len(Stil[Stil>stol])

Stilmat2=np.zeros((Atil.shape[0],rnew))
Stilmat2[:rnew,:rnew]=np.diag(Stil[:r])

newU21=np.concatenate((U1,np.zeros((2,6))), axis=1)
newU22=np.concatenate((np.zeros((6,2)),U2), axis=1)
newU2=np.concatenate((newU21,newU22), axis=0)

print(la.norm(A-(newU2@Util@Stilmat2@Vhtil[:r,:])))


(8, 8)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
2.5159333742054566e-15


In [118]:
print(Util)
print(Stil)
print(Vhtil.shape)
print(newVh)


[[ 2.85576556e-02 -2.21444136e-01  5.51193465e-01 -6.25306776e-01
  -3.88296408e-01 -3.23342010e-01  0.00000000e+00  0.00000000e+00]
 [ 9.90260821e-02  1.01702673e-01  5.10468848e-01  4.18472332e-01
  -4.72037652e-01  5.66862699e-01  0.00000000e+00  0.00000000e+00]
 [-7.85695248e-01 -5.68476153e-01  7.54991138e-02  2.31986474e-01
  -3.46944695e-16 -1.59594560e-16  0.00000000e+00  0.00000000e+00]
 [-6.00063211e-01  7.67002921e-01  1.21171116e-01 -1.92219204e-01
  -5.75928194e-16  9.15933995e-16  0.00000000e+00  0.00000000e+00]
 [ 1.08193318e-01  1.11117692e-01  5.57724969e-01  4.57211972e-01
   4.32041830e-01 -5.18832336e-01  0.00000000e+00  0.00000000e+00]
 [ 1.67218711e-02 -1.29666116e-01  3.22750095e-01 -3.66146978e-01
   6.63133631e-01  5.52204339e-01  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   

In [119]:

print(U)
print(Util)
print(la.norm(A-Util[:,:r]@Stilmat@newVh))
print(la.norm(A-Util[:,:r]@Stilmat2@Vhtil@newVh2))

[[ 4.73025855e-01  4.29903168e-01  4.12376332e-01 -2.49081833e-01
   1.20250594e-01  2.88188658e-01 -4.74070852e-01 -1.92555779e-01]
 [-2.04487816e-01  2.54988435e-02  1.15349183e-01 -7.09990068e-01
  -6.06392546e-01  1.21496485e-01  2.34154784e-01 -5.33050881e-02]
 [ 2.37087755e-01  2.68667815e-01 -6.73699861e-01 -4.82387907e-01
   3.01311628e-01 -2.63395250e-01 -1.18402440e-04  1.57707442e-01]
 [ 6.42480615e-01  2.18131709e-02  5.50354110e-02  1.76523076e-01
  -2.63330007e-01  1.50985577e-01  4.26656372e-01  5.27615916e-01]
 [ 3.06153923e-01  9.94587218e-03  2.86726505e-01 -9.66689478e-03
  -2.82742344e-02 -7.30241638e-01  2.99579308e-01 -4.47286569e-01]
 [-7.03018664e-03 -4.93755742e-01  4.00600449e-01 -4.05082010e-01
   5.75270799e-01  2.87395753e-02  1.59039280e-01  2.72997696e-01]
 [ 3.43599097e-01 -4.62924184e-01 -3.33770875e-01 -2.89176892e-02
   3.31049166e-02  4.29761346e-01  1.56202737e-01 -5.87547093e-01]
 [ 2.31515319e-01 -5.32618450e-01 -7.51273772e-02 -7.06593089e-02
  -

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 8 is different from 4)